import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import MainMenu from '@component/components/MainMenu'
import MainPage from '@component/components/MainPage'
import About from '@component/components/About'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <MainMenu/> */}
      <MainPage/>
      <About/>
    </>
  )
}
